import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

/* ══════════════════════════════════════════════════════════════
   Sphere — vite.config.ts
   PWA plugin caches the app shell + static assets so:
   ① App loads instantly on repeat visits (assets from cache)
   ② App opens when user is offline (shows cached pages)
   ③ Supabase API calls will still fail offline — that's expected.
      Only the UI shell and static assets are cached.
══════════════════════════════════════════════════════════════ */

export default defineConfig({
  plugins: [
    react(),

    VitePWA({
      registerType: "autoUpdate",

      /* Workbox config — what to cache */
      workbox: {
        /* Cache the app shell (HTML entry point) */
        navigateFallback: "/index.html",

        /* Pre-cache all JS, CSS, fonts, images generated by Vite */
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff,woff2}"],

        /* Runtime cache for Supabase assets (avatars, media) */
        runtimeCaching: [
          {
            /* Supabase storage — images and media */
            urlPattern: /^https:\/\/.*\.supabase\.co\/storage\/.*/i,
            handler: "CacheFirst",
            options: {
              cacheName: "supabase-storage",
              expiration: {
                maxEntries:    100,
                maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
              },
            },
          },
          {
            /* Google Fonts */
            urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
            handler:    "CacheFirst",
            options: {
              cacheName: "google-fonts",
              expiration: {
                maxEntries:    20,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
            },
          },
        ],
      },

      /* Web app manifest — enables "Add to Home Screen" */
      manifest: {
        name:             "Sphere",
        short_name:       "Sphere",
        description:      "Your world. Your voice.",
        theme_color:      "#2563eb",
        background_color: "#ffffff",
        display:          "standalone",
        orientation:      "portrait",
        start_url:        "/",
        scope:            "/",
        icons: [
          {
            src:     "/icons/icon-192.png",
            sizes:   "192x192",
            type:    "image/png",
            purpose: "any maskable",
          },
          {
            src:     "/icons/icon-512.png",
            sizes:   "512x512",
            type:    "image/png",
            purpose: "any maskable",
          },
        ],
      },

      /* Dev mode — set to true to test service worker in dev */
      devOptions: {
        enabled: false,
      },
    }),
  ],
});
